#!/usr/bin/python3.7

from concurrent.futures import ThreadPoolExecutor
import threading

with ThreadPoolExecutor(max_workers=1) as executor:
    future = executor.submit(pow, 323, 1235)
    print(future.result())

